name: Continuous Deployment
on:
  push:
    branches:
      - main

jobs:
  push_to_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Push changes to branch
        uses: ad-m/github-push-action@master
        with:
          branch: production
          force: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: push_to_branch

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout "production" branch
        uses: actions/checkout@v2
        with:
          ref: production

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Production Build
        run: npm run build:prod

      - name: Create folder for compiled files
        run: mkdir docs

      - name: Copy compiled files to folder
        run: cp -r dist/* docs/

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Compile and deploy"
          commit_options: "--author 'GitHub Actions <actions@github.com>'"