name: Continuous Deployment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Production Build
        run: npm run build:prod

      - name: Copy compiled files to folder
        run: cp -r dist/* docs/

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Compile and deploy"
          branch: production
          push_options: '--force'
          skip_dirty_check: true
          skip_fetch: true
          skip_checkout: true
