name: Continuous Deployment
on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Production Build
        run: npm run build:prod

      - name: Create folder for compiled files
        run: mkdir docs

      - name: Copy compiled files to folder
        run: cp -r dist/* docs/

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Compile and deploy"
          commit_options: "--author 'GitHub Actions <actions@github.com>'